name = input("What is the robot's model name?\n")
function = input("What is the primary function of the robot?\n")
creator = input("What is the creator's name?\n")
power = input("What powers the robot?\n")
number = input("What is the serial number of the robot?\n")
print(f"\n{"="*40}")
print(f"      ROBOTICS DIVISION - SPEC SHEET")
print(f"{"="*40}\n")
print(f"Model name:   [{name}]")
print(f"Serial number:   [{number}]")
print(f"Creator:  [{creator}]\n")
print(f"Full Designation: {creator}'s [{name}]\n")
print(f"{"-"*40}")
print(f"Primary function: [{function}]")
print(f"Power source: [{power}]")
print(f"{"-"*40}")
print("      STATUS: OPERATIONAL")
print(f"{"="*40}")
